workflows:
  android-release:
    name: Build Android AAB
    environment:
      flutter: stable
      java: 17
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.example.app"
        JAVA_TOOL_OPTIONS: "-Xmx4096m"
        GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Clean build directories
        script: |
          flutter clean
          rm -rf ~/.gradle/caches/*/fileHashes
      - name: Get dependencies
        script: flutter pub get
      - name: Build app bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your@email.com
  android-apk:
    name: Build Android APK
    environment:
      flutter: stable
      java: 17
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.example.app"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
  ios-release:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials
      vars:
        PACKAGE_NAME: "com.example.app"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
  web-release:
    name: Build Web App
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/web
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build web release
        script: flutter build web --release
    artifacts:
      - $BUILD_DIR/**
    publishing:
      email:
        recipients:
          - your@email.com
